### PR TITLE
Enable EZProxy pseudonymous identifiers

### PR DESCRIPTION
**Pull request by jsnshrmn**
Adds a git-ignored secrets file to store Identifier secrets
Bug: [T376708](https://phabricator.wikimedia.org/T376708)

### CODE REVIEW

**Review by katydidnot — APPROVED** [review]
This looks good to me based on spelunking through the admin dashboard and seeing the feature enabled. 
One question- where do the pseudo identifiers show up?

**Comment by jsnshrmn** [comment]
> This looks good to me based on spelunking through the admin dashboard and seeing the feature enabled. One question- where do the pseudo identifiers show up?

You have to search by username to get the corresponding pseudonymous id. These will only be generated after a user logs into one of the enabled sites.

**Review by suecarmol — APPROVED** [review]
Thanks for this PR!

**Comment by suecarmol** [comment]
Do we need to manually push these changes to staging/production?

**Pull request merged**
