### PR TITLE
Add cookies/ directory to gitignore

### PR DESCRIPTION
**Pull request by suecarmol**
This is for local environments only and shouldn't be added to the repo

### CODE REVIEW

**Comment by jsnshrmn** [comment]
when is the cookies directory getting created? I deployed this locally and didn't see it after clicking on a few resources

**Comment by suecarmol** [comment]
Have you tried accessing any of the resources in the library?

**Comment by suecarmol** [comment]
Got the cookies when trying to access Ancestry.com

**Comment by jsnshrmn** [comment]
hmm, I'm not able to make it happen:
image

**Review by jsnshrmn — APPROVED** [review]
Even though I wasn't able to get this directory generated, I can't imagine a scenario in which publishing cookies would be desirable; Approving so we don't need to spend any more time on it!

**Pull request merged**
